import { Metadata } from "next";
import Link from "next/link";
export const metadata: Metadata = {
  title: {
    absolute: ".",
    default: "Redlep | Home",
    template: "Redlep | %s",
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header
        style={{ backgroundColor: 'grey',padding: '1rem' }}>
          <p>Header</p>
          <Link href="/">Home</Link>
          <Link href="/about">About</Link>
          <Link href="/profile">Profile</Link>
          <Link href="/products">Products</Link>
          <Link href="/computers">Computers</Link>
          <Link href="/blog">Blog</Link>
        </header>
        {children}
        <footer
        style={{ backgroundColor: 'grey',padding: '1rem' }}>
          <p>Footer section</p>
        </footer>
      </body>
    </html>
  )
}
